-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 09:30:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agenda`;
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agenda`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `codigo_pais` INT NOT NULL,
  `codigo_area` INT NOT NULL,
  `numero` INT NOT NULL,
  `fk_pessoa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `telefone_pessoa` (`fk_pessoa` ASC) VISIBLE,
  CONSTRAINT `telefone_pessoa`
    FOREIGN KEY (`fk_pessoa`)
    REFERENCES `agenda`.`pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agenda`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_evento` DATE NOT NULL,
  `descricao` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`participacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`participacao` (
  `fk_evento` INT NOT NULL,
  `fk_pessoa` INT NOT NULL,
  PRIMARY KEY (`fk_evento`, `fk_pessoa`),
  INDEX `fk_evento_has_pessoa_pessoa1_idx` (`fk_pessoa` ASC) VISIBLE,
  INDEX `fk_evento_has_pessoa_evento1_idx` (`fk_evento` ASC) VISIBLE,
  CONSTRAINT `fk_evento_has_pessoa_evento1`
    FOREIGN KEY (`fk_evento`)
    REFERENCES `agenda`.`evento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_has_pessoa_pessoa1`
    FOREIGN KEY (`fk_pessoa`)
    REFERENCES `agenda`.`pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
